name: AgentLogScanner
options:
  bundleIdPrefix: com.ckorhonen
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  AgentLogScanner:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Resources
    info:
      path: Sources/Info.plist
      properties:
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: Agent Log Scanner
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSApplicationCategoryType: public.app-category.developer-tools
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
    entitlements:
      path: Sources/AgentLogScanner.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ckorhonen.agent-log-scanner
        PRODUCT_NAME: Agent Log Scanner
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
      configs:
        Debug:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          CODE_SIGN_ENTITLEMENTS: Sources/AgentLogScanner.entitlements
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -Osize

  AgentLogScannerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: AgentLogScanner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ckorhonen.agent-log-scanner.tests

schemes:
  AgentLogScanner:
    build:
      targets:
        AgentLogScanner: all
        AgentLogScannerTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - AgentLogScannerTests
    profile:
      config: Release
    archive:
      config: Release
